name: fantom
description: OpenAPI generator for Dart & Flutter
version: 0.0.1
homepage: https://github.com/6thsolution/fantom

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  fantom: main

dependencies:
  args: ^2.3.0
  cli_notify: ^0.0.3
  console: ^4.1.0
  cli_util: ^0.3.4
  io: ^1.0.3
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
